import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MyIFrame from "../components/MyIFrame"
import { AudioPlayer, PersistentPlayer } from 'decent-audio-player';
import { Song } from 'decent-audio-player/dist/types/shared';


const Home: NextPage = () => {
  const playlist = [{
    songUrl: "https://bafybeihfnzfu2hhrknrtz5hftxexu3vcy2ec4y4rtm5vy64njv4jdzluby.ipfs.nftstorage.link/",
    project: "Pizza",
    artist: "NOTAHASH",
    website: "https://twitter.com/Notahash",
    image: "https://bafybeige24gapqr3ez6vxnvpdhhoffvwsy7fbrytz6mwlfpfq2eozkdpzq.ipfs.nftstorage.link/"
  }, {
    songUrl: "https://bafybeideigtnn6kf7sslj6nlqcvlqw5lpnf7cv6u73cfu4pqn345myecs4.ipfs.nftstorage.link/",
    project: "Cryptopunks",
    artist: "NOTAHASH",
    website: "https://twitter.com/Notahash",
    image: "https://bafybeif43qxzrlpqyresd22zcccdosgbcedwrsa2oodhskuvvg7folusly.ipfs.nftstorage.link/"
  }, {
    songUrl: "https://bafybeifkhvz4p5phhdqppmmcrm3tyuryfmu5devo4fjdnxe5curulz5xqi.ipfs.nftstorage.link/",
    project: "The DAO",
    artist: "NOTAHASH",
    website: "https://twitter.com/Notahash",
    image: "https://bafybeigjwm3bvltddfn5vkpy5sio5fjyk3dd5gv6owfbdteyp4htpx5gla.ipfs.nftstorage.link/"
  }, {
    songUrl: "https://bafybeiehnu5i3grirqqg7iba5bimj5b7pnxgq6zd7jtreaa33shbxhppti.ipfs.nftstorage.link/",
    project: "Vitalik",
    artist: "NOTAHASH",
    website: "https://twitter.com/Notahash",
    image: "https://bafybeiejc46z5vky4b2mqx2pssuvwrboda5vuqoedt62odwom7ofmzmmwy.ipfs.nftstorage.link/",
     }, {
    songUrl: "https://bafybeiexi7oa6st34yrpn3ftewtncojaduvu5c5cbueh46zq3qpy4tb7ae.ipfs.dweb.link/",
    project: "Mt. Gox",
    artist: "NOTAHASH",
    website: "https://twitter.com/Notahash",
    image: "https://bafybeibvqllzwrgv27gkoqvwbpsanq5vpmwj3vqslnybrdye266muciowa.ipfs.nftstorage.link/",
     }, {
    songUrl: "https://bafybeickz5kpwmylb6itmw7py4dz3yn73l7thxcpwclnvgjneets3k5xmy.ipfs.nftstorage.link/",
    project: "Satoshi",
    artist: "NOTAHASH",
    website: "https://twitter.com/Notahash",
    image: "https://bafybeiawiel33fcfcnyejjtrhkcsfhazwzsdvrrskrp3b5xm2owc6yeuiu.ipfs.nftstorage.link/",
  }];

  return (
    <div className={styles.container}>
      <Head>
        <title>Notahash</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Notahash NFT Collection
        </h1>
        <AudioPlayer hasPlayer size={56} audioSrc='https://bafybeihfnzfu2hhrknrtz5hftxexu3vcy2ec4y4rtm5vy64njv4jdzluby.ipfs.nftstorage.link/' callbackAfterPlay={console.log} active />

    <PersistentPlayer playlist={playlist} />
      </main>
    </div>
  );
};

export default Home;
